#!/usr/bin/bash

# This file is based on vectors.pl in xv6.
# See COPYRIGHT for copyright information.

set -eu

# Generate vectors.S, the trap/interrupt entry points.
# There has to be one entry point per interrupt number
# since otherwise there's no way for trap() to discover
# the interrupt number.

echo "# generated by vectors.pl - do not edit"
echo "# handlers";
echo ".globl alltraps";

for i in $(seq 0 255); do
    echo ".globl vector$i"
    echo "vector$i:";
    if [[ !(($i -eq 8) || (($i -ge 10) && ($i -le 14)) || ($i -eq 17)) ]]; then
        echo "  pushq \$0"
    fi
    echo "  pushq \$$i"
    echo "  jmp alltraps"
done

echo ""
echo "# vector table"
echo ".data"
echo ".globl vectors"
echo "vectors:"

for i in $(seq 0 255); do
    echo "  .quad vector$i"
done

# sample output:
#   # handlers
#   .globl alltraps
#   .globl vector0
#   vector0:
#     pushq $0
#     pushq $0
#     jmp alltraps
#   ...
#
#   # vector table
#   .data
#   .globl vectors
#   vectors:
#     .quad vector0
#     .quad vector1
#     .quad vector2
#   ...

